# Includes RBAC resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
components:
  # Use resources for a size-S instance
  - ../../../components/sizes/s
  # This configures the Sourcegraph instance and networking to work in a k3s cluster
  - ../../../components/clusters/k3s
  - ../../../components/privileged
  - ../../../components/enable/service-discovery
