apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: index.docker.io/sourcegraph/migrator:6.11.1446@sha256:bc34a2b099cfa36e930f37a20356f51a52c0c2c6cc0dffd0e47539722bd5fa9f
          args: ["up"]
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
