apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: index.docker.io/sourcegraph/migrator:6.10.0@sha256:0abe2500352cf8129e3944bbb2a93b5ba571557a1711f127775a3774bc860c84
          args: ["up"]
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
