apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: index.docker.io/sourcegraph/migrator:5.3.0@sha256:8b0ac9c8112c9314f4b51cc73cbf325ad8a923fc30ef05c6ba1921e284ebf997
          args: ["up"]
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
