apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    description: Database migrator for Postgres databases
  labels:
    app.component.kubernetes/component: migrator
    deploy: sourcegraph
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: us-docker.pkg.dev/sourcegraph-images/internal/migrator:6.9.1277@sha256:3139de9d548b69ca683f5d78ba5b9f100e38b9067aac3bba5de7a8d62d0d8420
          args: ["up"]
          envFrom:
            - configMapRef:
                name: sourcegraph-frontend-env
          resources:
            limits:
              cpu: 500m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
      restartPolicy: OnFailure
  backoffLimit: 4
