apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles repository metadata (not Git data) lookups and updates from external code hosts and other similar services.
    kubectl.kubernetes.io/default-container: repo-updater
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: repo-updater
  name: repo-updater
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: repo-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: repo-updater
    spec:
      containers:
        - name: repo-updater
          image: us.gcr.io/sourcegraph-dev/repo-updater:wip_v5.2.123456@sha256:15b6874c53cacc4d29f290a98b65e266ab1e74dee8ecff8a6e407dfa675e3911
          env:
            # Required when service discovery is disabled
            - name: GITHUB_BASE_URL
              value: http://github-proxy:80
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 3182
              name: http
            - containerPort: 6060
              name: debug
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: debug
              scheme: HTTP
            periodSeconds: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: debug
              scheme: HTTP
            periodSeconds: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 500Mi
          securityContext:
            runAsGroup: 101
            runAsUser: 100
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
