apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: repo-updater
    app.kubernetes.io/component: repo-updater
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: repo-updater
spec:
  ports:
    - name: http
      port: 3182
      targetPort: http
    - name: debug
      port: 6060
      targetPort: debug
  selector:
    app: repo-updater
  type: ClusterIP
