apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: frontend
  name: sourcegraph-frontend
imagePullSecrets:
  - name: docker-registry
