apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for syntax highlighting operations.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: syntect-server
  name: syntect-server
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: syntect-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: syntect-server
    spec:
      containers:
        - name: syntect-server
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 101
            runAsUser: 100
          image: index.docker.io/sourcegraph/syntax-highlighter:6.6.2517@sha256:980d58f48e11823114e74cf1bfc05cebe3b7f6483f779441d240c820b1533d7d
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 9238
              name: http
            - containerPort: 6060
              name: debug
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            limits:
              cpu: "4"
              memory: 6G
            requests:
              cpu: 250m
              memory: 2G
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
