apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: syntect-server
    app.kubernetes.io/component: syntect-server
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: syntect-server
spec:
  ports:
    - name: http
      port: 9238
      targetPort: http
    - name: debug
      port: 6060
      targetPort: debug
  selector:
    app: syntect-server
  type: ClusterIP
