- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: transfer-cache
      image: index.docker.io/sourcegraph/alpine-3.14:insiders
      command:
        [
          "sh",
          "-c",
          'if [[ "$(stat -c ''%u'' /mnt/cache)" -ne 100 ]]; then chown -R 100:101 /mnt/cache; fi',
        ]
      volumeMounts:
        - mountPath: /mnt/cache
          name: cache-ssd
      securityContext:
        runAsUser: 0
