- op: replace
  path: /data/indexed-search_targets.yml
  value: |
    - labels:
        nodename: "sourcegraph-services"
        job: zoekt-indexserver
      targets:
        - indexed-search-0.indexed-search:6072
        - indexed-search-1.indexed-search:6072
    - labels:
        nodename: "sourcegraph-services"
        job: zoekt-webserver
      targets:
        - indexed-search-0.indexed-search:6070
        - indexed-search-1.indexed-search:6070
- op: replace
  path: /data/gitserver_targets.yml
  value: |
    - labels:
        nodename: "sourcegraph-services"
        job: gitserver
      targets:
        - gitserver-0.gitserver:6060
- op: replace
  path: /data/searcher_targets.yml
  value: |
    - labels:
        nodename: "sourcegraph-services"
        job: searcher
      targets:
        - searcher-0.searcher:6060
- op: replace
  path: /data/symbols_targets.yml
  value: |
    - labels:
        nodename: "sourcegraph-services"
        job: symbols
      targets:
        - symbols-0.symbols:6060
