apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../base/monitoring
  - patches/prometheus/prometheus.RoleBinding.yaml
components:
  - ../../remove/daemonset
patches:
  - path: patches/grafana/grafana.StatefulSet.yaml
  - path: patches/prometheus/prometheus.ConfigMap.yaml
  - path: patches/prometheus/prometheus.Deployment.yaml
