apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      fieldPath: data.TLS_SECRET_NAME
      kind: ConfigMap
      name: sourcegraph-kustomize-build-config
    targets:
      - fieldPaths:
          - spec.tls.*.secretName
        select:
          kind: Ingress
          name: sourcegraph-frontend
