apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: indexed-search
  name: indexed-search
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  serviceName: indexed-search
  template:
    metadata:
      labels:
        app: indexed-search
        deploy: sourcegraph
    spec:
      containers:
        - name: zoekt-webserver
          env:
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
            - name: OPENTELEMETRY_DISABLED
              value: "false"
          image: us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/indexed-searcher:6.4.2622@sha256:9acaf1998a3b211f3876a4baf8fd48ce4cd285acbaca7845f15ee7916152885b
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 6070
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 4G
            requests:
              cpu: 500m
              memory: 2G
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - mountPath: /data
              name: data
        - name: zoekt-indexserver
          env:
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
            - name: OPENTELEMETRY_DISABLED
              value: "false"
          image: us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/search-indexer:6.4.2622@sha256:1b31f9a3509a0764d65b4b7b3b4282c8ee817af0430b5f28e460c09257d3e5d4
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 6072
              name: index-http
          resources:
            # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
            # lower lag between a new commit and it being indexed for search.
            limits:
              cpu: "8"
              memory: 8G
            requests:
              cpu: "4"
              memory: 4G
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          deploy: sourcegraph
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            # The size of disk to used for search indexes.
            # This should typically be gitserver disk size multipled by the number of gitserver shards.
            storage: 200Gi
