apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
  - patches/frontend.Ingress.yaml
replacements:
  - source:
      fieldPath: data.HOST_DOMAIN
      kind: SourcegraphKustomizeConfig
      name: sourcegraph-kustomize-env
      version: v1
    targets:
      - select:
          kind: Ingress
          name: sourcegraph-frontend
        fieldPaths:
          - metadata.host
