apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      fieldPath: data.HOST_DOMAIN
      kind: SourcegraphKustomizeConfig
      name: sourcegraph-kustomize-config
      version: v1
    targets:
      - fieldPaths:
          - metadata.host
        select:
          kind: Ingress
          name: sourcegraph-frontend
patches:
  - path: patches/frontend.Ingress.yaml
