apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/securityContext-container-0.yaml
    target:
      group: apps
      kind: StatefulSet|Deployment
      name: .*
      version: v1
  - path: patches/securityContext-daemonset.yaml
    target:
      group: apps
      kind: DaemonSet
      name: otel-agent
      version: v1
  - path: patches/securityContext-databases.yaml
    target:
      group: apps
      kind: Deployment|StatefulSet
      name: codeinsights-db|codeintel-db|pgsql|sourcegraph-frontend
      version: v1
  - path: patches/securityContext-initContainer.yaml
    target:
      group: apps
      kind: Deployment|StatefulSet
      name: codeinsights-db|codeintel-db|pgsql|sourcegraph-frontend
      version: v1
  - path: patches/securityContext-container-1.yaml
    target:
      group: apps
      kind: Deployment|StatefulSet
      name: redis-cache|redis-store|indexed-search
      version: v1
