apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# DO NOT REMOVE: Handle updating endpoints configs for frontend
replacements: # DO NOT REMOVE
  - path: patches/endpoints-update.yaml # DO NOT REMOVE
########################## HOW TO USE ########################################
# Step 1: Uncomment the "name" and "count" for service you'd like to scale
# Step 2: Update the replica count value
# Step 3: Add this component to your overlay file
################################################################################
replicas:
  # - name: gitserver
  #   count: 7
  # - name: indexed-search
  #   count: 1
  # - name: searcher
  #   count: 1
  # - name: symbols
  #   count: 1
  # - name: sourcegraph-frontend
  #   count: 2
  # - name: precise-code-intel-worker
  #   count: 1
