apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sourcegraph-frontend
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb # aws load balancer controller ingressClass name
    # Add additional aws alb ingress controller supported annotations below
