apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - target:
      kind: Deployment|StatefulSet|DaemonSet
      name: .*
      group: apps
      version: v1
    path: patches/container-0.yaml
  - target:
      kind: StatefulSet|Deployment
      name: pgsql|codeinsights-db|codeintel-db|indexed-search|redis-cache|redis-store
      version: v1
    path: patches/container-1.yaml
  - target:
      kind: StatefulSet|Deployment
      name: pgsql|codeinsights-db|codeintel-db|sourcegraph-frontend
      version: v1
    path: patches/container-init.yaml
