apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - role-binding
  - ../../utils/endpoints
patches:
  - path: patches/sourcegraph-frontend.Role.yaml
  - path: patches/sourcegraph-frontend.ServiceAccount.yaml
  - path: patches/sourcegraph-frontend.Deployment.yaml
