apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
transformers:
  - |-
    fieldSpecs:
      - kind: Ingress
        name: sourcegraph-frontend
        path: metadata/annotations
        create: true
    apiVersion: builtin
    kind: AnnotationsTransformer
    metadata:
      name: annotations-transformer
    annotations:
      # Add new annotations below
      # EX. kubernetes.io/ingress.class: alb
