apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - target:
      kind: Deployment|StatefulSet|DaemonSet
      name: .*
      version: v1
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests
  - target:
      kind: StatefulSet|Deployment
      name: pgsql|codeinsights-db|codeintel-db|indexed-search|redis-cache|redis-store
      version: v1
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/1/resources/requests
  - target:
      kind: StatefulSet|Deployment
      name: pgsql|codeinsights-db|codeintel-db|sourcegraph-frontend
      version: v1
    patch: |-
      - op: remove
        path: /spec/template/spec/initContainers/0/resources/requests
