apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
  - ../../../base/monitoring
components:
  - ../../../components/resources/namespace
  - ../../../components/monitoring/tracing
  # Use resources for a size-XS instance
  - ../../../components/sizes/xs
  - ../../../components/clusters/aws/ebs-csi
