apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      fieldPath: data.HOST_DOMAIN
      kind: ConfigMap
      name: sourcegraph-kustomize-build-config
    targets:
      - fieldPaths:
          - spec.rules.*.host
        select:
          kind: Ingress
          name: sourcegraph-frontend
patches:
  - path: patches/frontend.Ingress.yaml
