apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../base/sourcegraph/frontend/rbac
patches:
  - path: patches/sourcegraph-frontend.Deployment.yaml
  - path: patches/sourcegraph-frontend.ConfigMap.yaml
