apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.ConfigMap.yaml
  - prometheus.ClusterRole.yaml
  - prometheus.ClusterRoleBinding.yaml
  - prometheus.ServiceAccount.yaml
