apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.ClusterRole.yaml
  - prometheus.ClusterRoleBinding.yaml
  - prometheus.ServiceAccount.yaml

# Create ConfigMap with prometheus.yml
configMapGenerator:
  - name: prometheus-rbac
    behavior: create
    files:
      - prometheus.yml=prometheus-rbac.yml
    literals:
      - extra_rules.yml=
      - prometheus_targets.yml=
    options:
      disableNameSuffixHash: true
      labels:
        deploy: sourcegraph
        sourcegraph-resource-requires: no-cluster-admin
        app.kubernetes.io/component: prometheus
