apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      name: searcher|symbols|indexed-search|grafana|gitserver
      group: apps
      version: v1
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        # This is the default storage class for minikube
        value: standard
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        # This is the default storage class for minikube
        value: standard
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace 
        path: /spec/resources/requests/storage
        value: 10Gi
