apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# To support searcher and symbols as both statefulset and deployment
patches:
  - path: patches/searcher/searcher.yaml
    target:
      group: apps
      kind: StatefulSet|Deployment
      name: searcher
      version: v1
  - path: patches/symbols/symbols.yaml
    target:
      group: apps
      kind: StatefulSet|Deployment
      name: symbols
      version: v1
  - path: patches/databases/securityContext.yaml
    target:
      group: apps
      kind: StatefulSet|Deployment
      name: codeinsights-db|codeintel-db|pgsql
      version: v1
  - path: patches/blobstore/blobstore.Deployment.yaml
  - path: patches/frontend/sourcegraph-frontend.Deployment.yaml
  - path: patches/github-proxy/github-proxy.Deployment.yaml
  - path: patches/gitserver/gitserver.StatefulSet.yaml
  - path: patches/indexed-search/indexed-search.StatefulSet.yaml
  - path: patches/precise-code-intel/worker.Deployment.yaml
  - path: patches/redis/redis-cache.Deployment.yaml
  - path: patches/redis/redis-store.Deployment.yaml
  - path: patches/repo-updater/repo-updater.Deployment.yaml
  - path: patches/syntect-server/syntect-server.Deployment.yaml
  - path: patches/worker/worker.Deployment.yaml
