steps:
  - label: ":k8s:"
    command: .buildkite/verify-yaml.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-label.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-rbac-labels.sh
    agents: { queue: standard }

  - label: ":git: :sleuth_or_spy:"
    command: .buildkite/verify-release/verify-release.sh
    agents: { queue: standard }

  - label: ":k8s: :sleuth_or_spy:"
    command: .buildkite/check-image-names.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-overlays.sh
    agents: { queue: standard }

  - label: "Release: test"
    if: "build.branch =~ /^wip_/"
    command: |
      wget https://storage.googleapis.com/buildkite_public_assets/sg-rfc795.tar.gz
      tar zxf sg-rfc795.tar.gz
      chmod +x ./sg-rfc795

      ./sg-rfc795 release run test --workdir=. --config-from-commit

  - wait

  - label: "Release: finalize"
    if: "build.branch =~ /^wip_/"
    command: |
      wget https://storage.googleapis.com/buildkite_public_assets/sg-rfc795.tar.gz
      tar zxf sg-rfc795.tar.gz
      chmod +x ./sg-rfc795

      ./sg-rfc795 release run internal finalize --workdir=. --config-from-commit
  - label: "Promote to public: finalize"
    if: "build.message =~ /^PRETEND PROMOTE RELEASE WIP/"
    command: |
      wget https://storage.googleapis.com/buildkite_public_assets/sg-rfc795.tar.gz
      tar zxf sg-rfc795.tar.gz
      chmod +x ./sg-rfc795

      ./sg-rfc795 release run promote-to-public finalize --workdir=. --config-from-commit
