steps:
  - label: ":k8s:"
    command: .buildkite/verify-yaml.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-label.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-rbac-labels.sh
    agents: { queue: standard }

  - label: ":git: :sleuth_or_spy:"
    command: .buildkite/verify-release/verify-release.sh
    agents: { queue: standard }

  - label: ":k8s: :sleuth_or_spy:"
    command: .buildkite/check-image-names.sh
    agents: { queue: standard }

  - label: ":k8s:"
    command: .buildkite/verify-overlays.sh
    agents: { queue: standard }

  - label: "Release: test"
    if: "build.branch =~ /^wip_/"
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run test --workdir=. --config-from-commit

  - wait

  - label: "Release: finalize"
    if: "build.branch =~ /^wip_/"
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run internal finalize --workdir=. --config-from-commit
  - label: "Promote to public: finalize"
    if: build.message =~ /^promote_release/ && build.branch =~ /^wip-release/
    plugins:
      - ssh://git@github.com/sourcegraph/sg-buildkite-plugin.git#main: ~
    command: |
      sg release run promote-to-public finalize --workdir=. --config-from-commit
