apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: sourcegraph
    target:
      group: apps
      kind: StatefulSet
      name: searcher|symbols|indexed-search|grafana|gitserver
      version: v1
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: sourcegraph
    target:
      kind: PersistentVolumeClaim
      name: .*
      version: v1
