apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      fieldPath: data.GKE_MANAGED_CERT_NAME
      kind: ConfigMap
      name: sourcegraph-kustomize-build-config
    targets:
      - fieldPaths:
          - metadata.annotations.[networking.gke.io/managed-certificates]
        select:
          kind: Ingress
          name: sourcegraph-frontend
patches:
  - path: patches/frontend.Ingress.yaml
