apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-config
# Refer to https://docs.sourcegraph.com/admin/executors/deploy_executors_binary#step-2-setup-environment-variables on how to populate these variables
data:
  EXECUTOR_FRONTEND_URL: "http://sourcegraph-frontend"
  EXECUTOR_MAXIMUM_NUM_JOBS: "8"
  # Used configure which queues Executors will process.
  # Can be "batches" or "codeintel"
  # Either set this or EXECUTOR_QUEUE_NAMES.
  EXECUTOR_QUEUE_NAME: ""
  # Used configure which queues Executors will process.
  # Can be "batches" or "codeintel" or "batches,codeintel"
  # Either set this or EXECUTOR_QUEUE_NAME.
  EXECUTOR_QUEUE_NAMES: ""
  EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY: "5Gi"
#  KUBERNETES_RUN_AS_USER: ""
#  KUBERNETES_RUN_AS_GROUP: ""
#  KUBERNETES_FS_GROUP: "1000"
