apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/pgsql.Deployment.yaml
    target:
      kind: StatefulSet
      name: pgsql
    options:
      allowKindChange: true
