apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  annotations:
    prometheus.io/port: "48080"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: cadvisor
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: cadvisor
spec:
  ports:
    - name: http # For querying metrics.
      port: 48080
  selector:
    app: cadvisor
  type: ClusterIP
