################################################################################################
# [BUILD CONFIGURATIONS]
# Some components read the configuration values in this file during the Kustomize build-process
#
# HOW TO USE:
# Enter the configuration values as instructed by components used in your kustomization.yaml
# Always refer to the component’s documentation or comments before updating
################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    description: Some components read the configuration values from the "data" field below during the build process. You only need to update this file if you are using components that require specific CONFIG_KEYS. If no components in your overlay require extra configuration, no update is necessary.
  labels:
    deploy: sourcegraph
  name: sourcegraph-kustomize-build-config
data:
  # example:
  EXAMPLE_CONFIG_KEY: example
  #-------- Update config options below ---------#
  # AWS_MANAGED_CERT_ARN: __placeholder__
  # GKE_MANAGED_CERT_NAME: __placeholder__
  # HOST_DOMAIN: __placeholder__
  # NEW_REDIS_CACHE_ENDPOINT: __placeholder__
  # NEW_REDIS_STORE_ENDPOINT: __placeholder__
  PRIVATE_REGISTRY: my-private-registry.io
  IMAGE_PULL_SECRET_NAME: secret-registry-key
  # SSD_NODE_PATH: __placeholder__
  # STORAGECLASS_NAME: __placeholder__
  # STORAGECLASS_PROVISIONER: __placeholder__
  # STORAGECLASS_PARAM_TYPE: __placeholder__
  # TLS_HOST: __placeholder__
  # TLS_INGRESS_CLASS_NAME: __placeholder__
  # TLS_CLUSTER_ISSUER: __placeholder__
  # TLS_SECRET_NAME: __placeholder__
