apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-config
  labels:
    app: executor
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
# Refer to the following on how to populate these variables
# https://docs.sourcegraph.com/admin/executors/deploy_executors_binary#step-2-setup-environment-variables
# https://docs.sourcegraph.com/admin/executors/deploy_executors_kubernetes#environment-variables
data:
  EXECUTOR_FRONTEND_URL: "http://sourcegraph.example.com"
  EXECUTOR_FRONTEND_PASSWORD: "our-shared-secret"
  EXECUTOR_USE_FIRECRACKER: "false"
  EXECUTOR_MAXIMUM_NUM_JOBS: "5"
  EXECUTOR_QUEUE_NAMES: "batches"
  EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY: "5Gi"
  EXECUTOR_KUBERNETES_PERSISTENCE_VOLUME_NAME: "sg-executor-pvc"
  EXECUTOR_KUBERNETES_POD_AFFINITY: '[{"labelSelector": {"matchExpressions": [{"key": "app", "operator": "In", "values": ["executor"]}]}, "topologyKey": "kubernetes.io/hostname"}]'
