apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac
  - executor.ConfigMap.yaml
  - executor.Deployment.yaml
  - executor.PersistentVolumeClaim.yaml
  - executor.Service.yaml
patches:
  - path: ../patches/executor.ConfigMap.yaml
