apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-executor-batches
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
spec:
  selector:
    matchLabels:
      app: sg-executor-batches
  template:
    metadata:
      namespace: default
      labels:
        app: sg-executor-batches
    spec:
      securityContext:
        # TODO: not allowed to create dirs with default sourcegraph user
        runAsUser: 0
      serviceAccountName: sg-executor-service-account
      containers:
        - name: sg-executor-batches
          image: sourcegraph/executor-kubernetes:main-dry-run-rc-k8s-directory-creation_215977_2023-04-28_5.0-9b4f55fbff85@sha256:e11a50201f4e619f25b35edc26b037dc4f931073dc1bb10f34bbc17d670bd88d
          imagePullPolicy: IfNotPresent
          # TODO: how to kustomize these env vars properly?
          env:
            - name: EXECUTOR_FRONTEND_URL
              value: http://sourcegraph-frontend:30080
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-frontend-password
                  key: EXECUTOR_FRONTEND_PASSWORD
            - name: EXECUTOR_QUEUE_NAME
              value: batches
            - name: EXECUTOR_MAXIMUM_NUM_JOBS
              value: "10"
            - name: SRC_LOG_LEVEL
              value: info
            - name: SRC_LOG_FORMAT
              value: condensed
            - name: SRC_TRACE_LOG
              value: "false"
            - name: EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY
              value: 1Gi
            - name: EXECUTOR_DOCKER_ADD_HOST_GATEWAY
              # For local deployments the host is 'host.docker.internal' and this needs to be true
              value: "false"
            # Useful for debugging.
            - name: EXECUTOR_KUBERNETES_NAMESPACE
              value: sourcegraph
            - name: KUBERNETES_KEEP_JOBS
              value: "false"
            - name: EXECUTOR_KEEP_WORKSPACES
              value: "false"
            - name: EXECUTOR_KUBERNETES_PERSISTENCE_VOLUME_NAME
              value: sg-executor-pvc-batches
          volumeMounts:
            - mountPath: /data
              name: sg-executor-volume-batches
      volumes:
        - name: sg-executor-volume-batches
          persistentVolumeClaim:
            claimName: sg-executor-pvc-batches
