apiVersion: v1
kind: Service
metadata:
  name: sg-executor-codeintel
  labels:
    app: sg-executor-codeintel
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
spec:
  selector:
    app: sg-executor-codeintel
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  # For development purposes.
#  type: LoadBalancer
