apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-config
  labels:
    app: executor
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
# Refer to https://docs.sourcegraph.com/admin/executors/deploy_executors_binary#step-2-setup-environment-variables on how to populate these variables
data:
  EXECUTOR_FRONTEND_URL: "http://sourcegraph.example.com"
  EXECUTOR_FRONTEND_PASSWORD: "our-shared-secret"
  EXECUTOR_USE_FIRECRACKER: "false"
  EXECUTOR_MAXIMUM_NUM_JOBS: "8"
  # Used configure which queues Executors will process.
  # Can be "batches", "codeintel", or "batches,codeintel"
  EXECUTOR_QUEUE_NAMES: ""

  # For docker-in-docker (dind) executor
  # DOCKER_HOST: "tcp://localhost:2375"
  # Note: Must match the mount point shared with the docker-in-docker (dind) sidecar
  # TMPDIR: "/scratch"

  # For native kubernetes executor
  EXECUTOR_KUBERNETES_RESOURCE_REQUEST_MEMORY: "5Gi"
  EXECUTOR_KUBERNETES_PERSISTENCE_VOLUME_NAME: "sg-executor-pvc"
  EXECUTOR_KUBERNETES_POD_AFFINITY: '[{"labelSelector": {"matchExpressions": [{"key": "app", "operator": "In", "values": ["executor"]}]}, "topologyKey": "kubernetes.io/hostname"}]'
