apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sg-executor-pvc-codeintel
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
