apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles embeddings searches
  name: embeddings
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: embeddings
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: embeddings
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: embeddings
    spec:
      containers:
        - name: embeddings
          image: us.gcr.io/sourcegraph-dev/embeddings:wip_v5.2.123456@sha256:b15240f6e8822427bde1a10a93b8651adb4f907fb331cefe9c01473ad5e6b5a8
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          envFrom:
            - configMapRef:
                name: embeddings-backend
          ports:
            - containerPort: 9991
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "8"
              memory: 64G
            requests:
              cpu: "4"
              memory: 32G
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 101
            runAsUser: 100
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
