apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: embeddings
    app.kubernetes.io/component: embeddings
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: embeddings-backend
data:
  EMBEDDINGS_UPLOAD_BACKEND: blobstore
  EMBEDDINGS_UPLOAD_AWS_ENDPOINT: http://blobstore:9000
