apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Sourcegraph Main Stacks
  - ../../base/sourcegraph
components:
  # Update and generate resources for the old cluster
  # This includes the monitoring stack
  - ../../components/old-cluster
