apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Sourcegraph Main Stack
  - ../../base/sourcegraph
components:
  # Update and generate resources for the old cluster
  # This includes the monitoring stack
  - ../../components/clusters/old-base
