apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
# Run all services with default values
resources:
  # [REQUIRED: BUILD CONFIG] Update this file when using components that have "CONFIG KEYS"
  - buildConfig.yaml # -- Update the CONFIG Key values in buildConfig.yaml when instructed
  - ../../base/sourcegraph
  - ../../base/monitoring
components:
  - ../../components/resources/namespace
  - ../../components/monitoring/tracing
  - ../../components/enable/private-registry
  - ../../components/resources/imagepullsecrets
