apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Add RBAC resources for monitoring services
components:
  - ../rbacs
# Remove security context
patchesJson6902:
  - target:
      kind: StatefulSet|Deployment
      name: grafana|prometheus|otel-collector
      group: apps
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          runAsUser: 0
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
  - target:
      kind: DaemonSet
      name: otel-agent
      group: apps
      version: v1
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
