apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - options:
      allowKindChange: true
    path: patches/searcher.Deployment.yaml
    target:
      kind: StatefulSet
      name: searcher
  - patch: |-
      - op: remove
        path: /spec/clusterIP
    target:
      kind: Service
      name: searcher
