apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: embeddings-backend
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: embeddings
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: embeddings
