apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
    # Monitoring Stack
  - ../../../base/monitoring
components:
  # Use resources for a size-XS instance
  - ../../../components/sizes/xs
