apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      fieldPath: data.AWS_MANAGED_CERT_ARN
      kind: ConfigMap
      name: sourcegraph-kustomize-build-config
    targets:
      - fieldPaths:
          - metadata.annotations.[alb.ingress.kubernetes.io/certificate-arn]
        select:
          kind: Ingress
          name: sourcegraph-frontend
patches:
  - path: patches/frontend.Ingress.yaml
