apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.Deployment.yaml
  - prometheus.PersistentVolumeClaim.yaml
  - prometheus.Service.yaml

# Create ConfigMap with prometheus.yml
configMapGenerator:
  - name: prometheus
    behavior: create
    files:
      - prometheus.yml
    literals:
      - extra_rules.yml=
      - prometheus_targets.yml=
    options:
      disableNameSuffixHash: true
      labels:
        deploy: sourcegraph
        sourcegraph-resource-requires: no-cluster-admin
        app.kubernetes.io/component: prometheus
