apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.ConfigMap.yaml
  - prometheus.Deployment.yaml
  - prometheus.PersistentVolumeClaim.yaml
  - prometheus.Service.yaml
