apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sourcegraph-frontend
    app.kubernetes.io/component: frontend
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: sourcegraph-frontend-env
data:
  DEPLOY_TYPE: kustomize
  PGDATABASE: sg
  PGHOST: pgsql
  PGPORT: "5432"
  PGSSLMODE: disable
  PGUSER: sg
  CODEINSIGHTS_PGDATASOURCE: postgres://postgres:password@codeinsights-db:5432/postgres
  CODEINTEL_PGDATABASE: sg
  CODEINTEL_PGHOST: codeintel-db
  CODEINTEL_PGPORT: "5432"
  CODEINTEL_PGSSLMODE: disable
  CODEINTEL_PGUSER: sg
  GRAFANA_SERVER_URL: http://grafana:30070
  PROMETHEUS_URL: http://prometheus:30090
  SRC_GIT_SERVERS: gitserver-0.gitserver:3178
  SEARCHER_URL: http://searcher-0.searcher:3181
  INDEXED_SEARCH_SERVERS: indexed-search-0.indexed-search:6070
