apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../base/monitoring
  - ../../../base/monitoring/cadvisor
components:
  - ../../../components/monitoring/privileged
  - ../../storage-class/k3s
patchesStrategicMerge:
  - patches/prometheus.ConfigMap.yaml
