apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    description: Forwards telemetry data to the OpenTelemetry Collector Deployment.
    prometheus.io/port: "8888"
    sourcegraph.prometheus/scrape: "true"
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: otel-collector
  name: otel-agent
spec:
  selector:
    matchLabels:
      app: otel-agent
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: otel-agent
      labels:
        deploy: sourcegraph
        app: otel-agent
    spec:
      containers:
        - name: otel-agent
          image: us-docker.pkg.dev/sourcegraph-images/internal/opentelemetry-collector:6.7.229@sha256:820ae65fa8a6cc9e55e7b908c21a8ebc764d23fa68071686032b0778c4819a3a
          command:
            - "/bin/otelcol-sourcegraph"
            - "--config=/etc/otel-agent/config.yaml"
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
            requests:
              cpu: "100m"
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
          ports:
            - containerPort: 55679
              name: zpages
            - containerPort: 4317
              hostPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              hostPort: 4318
              name: otlp-http
            - containerPort: 8888
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /etc/otel-agent
      terminationGracePeriodSeconds: 120
      volumes:
        - name: config
          configMap:
            name: otel-agent
            items:
              - key: config.yaml
                path: config.yaml
