apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/databases.yaml
    target:
      group: apps
      kind: StatefulSet|Deployment
      name: codeinsights-db|codeintel-db|pgsql
      version: v1
