apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - target:
      kind: StatefulSet|Deployment
      name: codeinsights-db|codeintel-db|pgsql
      group: apps
      version: v1
    path: patches/databases.yaml
