apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Stores clones of repositories to perform Git operations.
    kubectl.kubernetes.io/default-container: gitserver
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: gitserver
  name: gitserver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitserver
  serviceName: gitserver
  template:
    metadata:
      labels:
        app: gitserver
        group: backend
        type: gitserver
        deploy: sourcegraph
    spec:
      containers:
        - name: gitserver
          args: ["run"]
          env:
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          image: index.docker.io/sourcegraph/gitserver:6.4.3889@sha256:36c2fbe144c27eed2825b8f2b1356a06e4e4e96f91ce413cc8af896ce341904a
          terminationMessagePolicy: FallbackToLogsOnError
          # Temporary: when migrating from repo names to repo IDs on disk,
          # gitserver can take a little while to start up. To avoid killing the
          # pod because of a failed liveness probe, we give it 2 minutes to start up.
          startupProbe:
            tcpSocket:
              port: rpc
            failureThreshold: 120
            periodSeconds: 1
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: rpc
            timeoutSeconds: 5
          ports:
            - containerPort: 3178
              protocol: TCP
              name: rpc
          resources:
            limits:
              cpu: "4"
              memory: 8G
            requests:
              cpu: "4"
              memory: 8G
          securityContext:
            runAsUser: 100
            runAsGroup: 101
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /data/repos
              name: repos
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: repos
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: repos
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            # The size of disk used to mirror your git repositories.
            # If you change this, also change indexed-search's disk size.
            storage: 200Gi
