apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Stores clones of repositories to perform Git operations.
    kubectl.kubernetes.io/default-container: gitserver
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: gitserver
  name: gitserver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitserver
  serviceName: gitserver
  template:
    metadata:
      labels:
        app: gitserver
        group: backend
        type: gitserver
        deploy: sourcegraph
    spec:
      containers:
        - name: gitserver
          args: ["run"]
          env:
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          image: us.gcr.io/sourcegraph-dev/gitserver:wip_v5.2.123456@sha256:24e4a8729c4b2bc352c131d1d986f2abeca5661a714286f20c2ea43ca9ab91a5
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: rpc
            timeoutSeconds: 5
          ports:
            - containerPort: 3178
              protocol: TCP
              name: rpc
          resources:
            limits:
              cpu: "4"
              memory: 8G
            requests:
              cpu: "4"
              memory: 8G
          securityContext:
            runAsUser: 100
            runAsGroup: 101
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /data/repos
              name: repos
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: repos
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: repos
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            # The size of disk used to mirror your git repositories.
            # If you change this, also change indexed-search's disk size.
            storage: 200Gi
