apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Sourcegraph Main Stack
  - ../../base/sourcegraph
  # Monitoring Stack
  - ../../base/monitoring
components:
  - ../../components/resources/ci-volume
  - ../../components/remove/resources
  - ../../components/remove/pvcs
