apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Backend for text search operations.
    kubectl.kubernetes.io/default-container: searcher
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: searcher
  name: searcher
spec:
  serviceName: searcher
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: searcher
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: searcher
    spec:
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: searcher
          env:
            - name: SEARCHER_CACHE_SIZE_MB
              value: "25000"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CACHE_DIR
              value: /mnt/cache/$(POD_NAME)
            # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          image: index.docker.io/sourcegraph/searcher:5.0.4@sha256:8cbe84397f48e2c338e3ab20f62a8b18c856963317294f0205cf6d242d893d14
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 3181
              name: http
            - containerPort: 6060
              name: debug
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 2G
            requests:
              cpu: 500m
              memory: 500M
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 101
            runAsUser: 100
          volumeMounts:
            - mountPath: /mnt/cache
              name: cache
      volumes:
        - emptyDir: {}
          name: cache
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30G
