apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
components:
  - ../../components/utils/migrator

# Update migration commands under the value field
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - upgrade
          - -from=v3.36
          - -to=v4.0
    target:
      kind: Job
      name: migrator
      version: v1

# Update env vars for migrator below
configMapGenerator:
  - behavior: merge
    name: sourcegraph-frontend-env
    literals:
      - PGHOST=pgsql
      - PGPORT=5432
      - PGUSER=sg
      - PGPASSWORD=sg
      - PGDATABASE=sg
      - PGSSLMODE=disable
      - CODEINTEL_PGHOST=codeintel-db
      - CODEINTEL_PGPORT=5432
      - CODEINTEL_PGUSER=sg
      - CODEINTEL_PGPASSWORD=sg
      - CODEINTEL_PGDATABASE=sg
      - CODEINTEL_PGSSLMODE=disable
      - CODEINSIGHTS_PGHOST=codeinsights-db
      - CODEINSIGHTS_PGPORT=5432
      - CODEINSIGHTS_PGUSER=postgres
      - CODEINSIGHTS_PGPASSWORD=password
      - CODEINSIGHTS_PGDATABASE=postgres
      - CODEINSIGHTS_PGSSLMODE=disable
