apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: executor-sourcegraph
resources:
  # Sourcegraph Main Stack
  - ../../base/sourcegraph
  - ../../base/monitoring
components:
  # Native Kubernetes Executors
  - ../../components/executors/k8s
patches:
  - path: patches/executor.ConfigMap.yaml
secretGenerator:
  - name: executor-secret
    behavior: create
    literals:
      - password=our-shared-secret
