apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - patches/frontend.BackendConfig.yaml
patches:
  - path: patches/frontend.Service.yaml
  - path: patches/frontend-internal.Service.yaml
  - path: patches/frontend.Ingress.yaml
