apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: pgsql
    app.kubernetes.io/component: pgsql
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: pgsql
spec:
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql
    - name: pgsql-exporter
      port: 9187
      targetPort: pgsql-exporter
  selector:
    app: pgsql
  type: ClusterIP
