apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../base/monitoring/grafana/rbac
  - ../../../base/monitoring/prometheus/rbac
patches:
  - path: prometheus/prometheus.Deployment.yaml
  - path: grafana/grafana.StatefulSet.yaml
  - path: grafana/grafana.Dashboards.ConfigMap.yaml
  - patch: |-
      - op: remove
        path: /data/prometheus.yml
      - op: remove
        path: /data/extra_rules.yml
    target:
      name: prometheus
      version: v1
      kind: ConfigMap
