apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - grafana/grafana.ServiceAccount.yaml
  - prometheus/prometheus.ClusterRole.yaml
  - prometheus/prometheus.ClusterRoleBinding.yaml
  - prometheus/prometheus.ServiceAccount.yaml
patches:
  - path: prometheus/prometheus.ConfigMap.yaml
  - path: grafana/grafana.StatefulSet.yaml
  - path: prometheus/prometheus.Deployment.yaml
  - path: grafana/grafana.Dashboards.ConfigMap.yaml
