apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - grafana/grafana.ServiceAccount.yaml
  - prometheus/prometheus.ClusterRole.yaml
  - prometheus/prometheus.ClusterRoleBinding.yaml
  - prometheus/prometheus.ServiceAccount.yaml
patchesStrategicMerge:
  - prometheus/prometheus.ConfigMap.yaml
