apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: jaeger
    app: jaeger
    app.kubernetes.io/name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        deploy: sourcegraph
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      containers:
        - name: jaeger
          image: index.docker.io/sourcegraph/jaeger-all-in-one:7.1.2426@sha256:65756fcd95c9475c3a2b0c7efdd5a4d43c1a5a0786cfefc3599d9a3f09823b94
          args: ["--config=/etc/jaeger/jaeger-config.yaml"]
          ports:
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              name: http
              protocol: TCP
            - containerPort: 4317
              name: grpc-otlp
              protocol: TCP
            - containerPort: 4318
              name: http-otlp
              protocol: TCP
            - containerPort: 13133
              name: health
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/status"
              port: 13133
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: 500m
              memory: 500M
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
