apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: jaeger
    app: jaeger
    app.kubernetes.io/name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        deploy: sourcegraph
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      containers:
        - name: jaeger
          image: index.docker.io/sourcegraph/jaeger-all-in-one:5.3.0@sha256:17c72abf02f5859fca6bd5826ef94f8f870e16fd8a088fce1ad90363693b90fb
          args: ["--memory.max-traces=20000"]
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: 500m
              memory: 500M
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
      securityContext:
        runAsUser: 100
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
