apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: jaeger
    app: jaeger
    app.kubernetes.io/name: jaeger
spec:
  ports:
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: http-otlp
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: grpc-otlp
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
  type: ClusterIP
