apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/sourcegraph
  - ../../../base/monitoring
components:
  - ../../../components/monitoring/grafana/dashboards
  - ../../../components/monitoring/grafana/dashboards/process
  - ../../../components/sizes/xs
  - ../../../components/clusters/gke/configure
