apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Code Insights Postgres DB instance.
  labels:
    app.kubernetes.io/component: codeinsights-db
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: codeinsights-db
spec:
  replicas: 1
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: codeinsights-db
  serviceName: codeinsights-db
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: codeinsights-db
        group: backend
    spec:
      initContainers:
        - name: correct-data-dir-permissions
          image: us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/alpine-3.14:6.0.2687@sha256:f276631b5dcd61f57ec8da723b316c1c730fc667064b584e647601e816fe9679
          command: ["sh", "-c", "if [ -d /var/lib/postgresql/data/pgdata ]; then chmod 750 /var/lib/postgresql/data/pgdata; fi"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: disk
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsGroup: 70
            runAsUser: 70
      containers:
        - name: codeinsights
          image: us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/postgresql-16-codeinsights:6.0.2687@sha256:e354060521e22f383754afe5638980a36e83ef04648f64ade33d5fb8a2bf3473
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD # Accessible by Sourcegraph applications on the network only, so password auth is not used.
              value: password
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRESQL_CONF_DIR
              value: "/conf"
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 5432
              name: codeinsights-db
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: "4"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 70
            runAsUser: 70
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: disk
            - mountPath: /conf
              name: codeinsights-conf
        - env:
            - name: DATA_SOURCE_NAME
              value: postgres://postgres:@localhost:5432/?sslmode=disable
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /config/code_insights_queries.yaml
          image: us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/postgres_exporter:6.0.2687@sha256:97800ae975ffa191f1d2ecfdde58ea465afe29b3ab45653fa672f1bb3007fa3f
          terminationMessagePolicy: FallbackToLogsOnError
          name: pgsql-exporter
          ports:
            - name: pgsql-exporter
              containerPort: 9187
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsUser: 70
        fsGroup: 70
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: codeinsights-db
        - name: codeinsights-conf
          configMap:
            # 511 in decimal = 0777 in octal
            defaultMode: 511
            name: codeinsights-db-conf
