apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    description: Code Insights Postgres DB instance.
  labels:
    app.kubernetes.io/component: codeinsights-db
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: codeinsights-db
spec:
  replicas: 1
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: codeinsights-db
  serviceName: codeinsights-db
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: codeinsights-db
        group: backend
    spec:
      initContainers:
        - name: correct-data-dir-permissions
          image: us-docker.pkg.dev/sourcegraph-images/internal/alpine-3.14:7.0.2178@sha256:0e4f5a8748536f1f3c7b18dfa2c1e1ce563f6c7caee98fefb5450a8788813e99
          command: ["sh", "-c", "if [ -d /var/lib/postgresql/data/pgdata ]; then chmod 750 /var/lib/postgresql/data/pgdata; fi"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: disk
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          securityContext:
            # Required to prevent escalations to root.
            allowPrivilegeEscalation: false
            runAsGroup: 70
            runAsUser: 70
      containers:
        - name: codeinsights
          image: us-docker.pkg.dev/sourcegraph-images/internal/postgresql-16-codeinsights:7.0.2178@sha256:21d2519f4376331083f68168c74d3f6ae8ec7b9dec969782eb0853d5913e45e9
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD # Accessible by Sourcegraph applications on the network only, so password auth is not used.
              value: password
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRESQL_CONF_DIR
              value: "/conf"
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 5432
              name: codeinsights-db
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: "4"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 70
            runAsUser: 70
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: disk
            - mountPath: /conf
              name: codeinsights-conf
        - env:
            - name: DATA_SOURCE_NAME
              value: postgres://postgres:@localhost:5432/?sslmode=disable
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /config/code_insights_queries.yaml
          image: us-docker.pkg.dev/sourcegraph-images/internal/postgres_exporter:7.0.2178@sha256:2fdae79edc3d18182ece4060d3f4f0ef455c70d9487bc366fba0bca78f6fad20
          terminationMessagePolicy: FallbackToLogsOnError
          name: pgsql-exporter
          ports:
            - name: pgsql-exporter
              containerPort: 9187
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsUser: 70
        fsGroup: 70
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: codeinsights-db
        - name: codeinsights-conf
          configMap:
            # 511 in decimal = 0777 in octal
            defaultMode: 511
            name: codeinsights-db-conf
