kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sourcegraph
  labels:
    deploy: sourcegraph
reclaimPolicy: Retain
allowVolumeExpansion: true
# Read https://kubernetes.io/docs/concepts/storage/storage-classes/ to configure the "provisioner" and "parameters" fields for your cloud provider.
# SSDs are highly recommended!
provisioner: $(STORAGECLASS_PROVISIONER)
parameters:
  type: $(STORAGECLASS_PARAM_TYPE) # This configures SSDs (recommended).
