apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
  - ../../../base/monitoring
components:
  - ../../../components/monitoring/cadvisor
  - ../../../components/monitoring/privileged
  # Use resources for a size-XS instance
  - ../../../components/sizes/xs
  - ../../../components/privileged
  - ../../../components/clusters/gke/configure
  - ../../../components/enable/service-discovery
