apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
resources:
  # Sourcegraph Main Stack
  - ../../base/sourcegraph
components:
  - ../../components/resources/namespace
  - ../../components/clusters/minikube
