apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      serviceAccountName: prometheus
      volumes:
        - configMap:
            defaultMode: 0777
            name: prometheus-rbac
          name: config
