apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sourcegraph
  - ../../base/monitoring
components:
  - ../../components/sizes/xs
  - ../../components/clusters/gke/configure
