apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbols
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: symbols
          env:
            - name: SYMBOLS_CACHE_SIZE_MB
              valueFrom:
                resourceFieldRef:
                  containerName: symbols
                  resource: requests.ephemeral-storage
                  divisor: 1M
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CACHE_DIR
              value: /mnt/cache/$(POD_NAME)
              # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_AGENT_HOST):4317
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: "12G"
              memory: 2G
            requests:
              cpu: 500m
              ephemeral-storage: "10G"
              memory: 500M
          volumeMounts:
            - mountPath: /mnt/cache
              name: cache-ssd
      securityContext:
        runAsUser: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - emptyDir: {}
          name: cache-ssd
  updateStrategy:
    $patch: delete
  volumeClaimTemplates:
  serviceName:
