apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
    # Monitoring Stack
  - ../../../base/monitoring
components:
  - ../../../components/resources/namespace
  - ../../../components/sizes/xl
