apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - options:
      allowKindChange: true
    path: patches/searcher.StatefulSet.yaml
    target:
      kind: Deployment
      name: searcher
