apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../storage-class/minikube
patches:
  - target:
      kind: Deployment
      name: .*
      group: apps
      version: v1
    path: patches/remove-deployment-resources-container-0.yaml
  - target:
      kind: Deployment
      name: pgsql|redis-cache|redis-store|codeintel-db|codeinsights-db
      group: apps
      version: v1
    path: patches/remove-deployment-resources-container-1.yaml
  - target:
      kind: StatefulSet
      name: .*
      group: apps
      version: v1
    path: patches/remove-statefulset-resources-container-0.yaml
  - target:
      kind: StatefulSet
      name: indexed-search
      group: apps
      version: v1
    path: patches/remove-statefulset-resources-container-1.yaml
  - target:
      kind: Deployment
      name: sourcegraph-frontend|pgsql|codeintel-db|codeinsights-db
      group: apps
      version: v1
    path: patches/remove-deployment-resources-container-init.yaml
