apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../storage-class/minikube
patches:
  - path: patches/remove-deployment-resources-container-0.yaml
    target:
      group: apps
      kind: Deployment
      name: .*
      version: v1
  - path: patches/remove-deployment-resources-container-1.yaml
    target:
      group: apps
      kind: Deployment|StatefulSet
      name: pgsql|redis-cache|redis-store|codeintel-db|codeinsights-db
      version: v1
  - path: patches/remove-statefulset-resources-container-0.yaml
    target:
      group: apps
      kind: StatefulSet
      name: .*
      version: v1
  - path: patches/remove-statefulset-resources-container-1.yaml
    target:
      group: apps
      kind: StatefulSet
      name: indexed-search
      version: v1
  - path: patches/remove-deployment-resources-container-init.yaml
    target:
      group: apps
      kind: Deployment|StatefulSet
      name: sourcegraph-frontend|pgsql|codeintel-db|codeinsights-db
      version: v1
