apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: executor
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
  name: docker-config
