apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: pgsql-conf
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: pgsql
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: pgsql
