apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: remove
        path: /spec
    target:
      kind: .*
      name: otel-collector|otel-agent
      version: v1
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: otel-agent
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: otel-agent
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: otel-collector
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: otel-collector
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: otel-collector
