apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../base/monitoring
components:
  - ../../remove/daemonset
  - ../../remove/prometheus
patches:
  - path: patches/grafana/grafana.StatefulSet.yaml
