apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../resources/lower-requests
patchesStrategicMerge:
  - patches/resources.yaml
  - patches/endpoints.yaml
# To support searcher and symbols as both statefulset and deployment
patchesJson6902:
  - target:
      kind: StatefulSet|Deployment
      name: searcher
      group: apps
      version: v1
    path: patches/searcher.yaml
  - target:
      kind: StatefulSet|Deployment
      name: symbols
      group: apps
      version: v1
    path: patches/symbols.yaml
  - target:
      kind: StatefulSet|Deployment
      name: pgsql
      group: apps
      version: v1
    path: patches/pgsql.yaml
  - target:
      kind: StatefulSet|Deployment
      name: codeinsights-db
      group: apps
      version: v1
    path: patches/codeinsights-db.yaml
  - target:
      kind: StatefulSet|Deployment
      name: codeintel-db
      group: apps
      version: v1
    path: patches/codeintel-db.yaml
  - target:
      kind: ConfigMap
      name: prometheus
      version: v1
    path: patches/prometheus.yaml
