apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  labels:
    category: rbac
    deploy: sourcegraph
    sourcegraph-resource-requires: cluster-admin
    app.kubernetes.io/component: executor
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
