apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Redis for storing short-lived caches.
    kubectl.kubernetes.io/default-container: redis-cache
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: redis
  name: redis-cache
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: redis-cache
    spec:
      containers:
        - name: redis-cache
          image: index.docker.io/sourcegraph/redis-cache:7.2.1943@sha256:65e6e84bfaa55a1e998fbe9f3ea1424af1d40637fab252494ada5b47889ed408
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: redis
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  PASS_CHECK=$(grep -h "requirepass" /etc/redis/redis.conf | cut -d ' ' -f 2)
                  if [ ! -z "$PASS_CHECK" ]; then
                    export REDISCLI_AUTH="$PASS_CHECK"
                  fi
                  response=$(
                    redis-cli ping
                  )
                  if [ "$response" != "PONG" ]; then
                    echo "$response"
                    exit 1
                  fi
          resources:
            limits:
              cpu: "1"
              memory: 7Gi
            requests:
              cpu: "1"
              memory: 7Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 999
          volumeMounts:
            - mountPath: /redis-data
              name: redis-data
        - name: redis-exporter
          image: index.docker.io/sourcegraph/redis_exporter:7.2.1943@sha256:4b15ed3fb20e1ea5b54d2d074c986698f3c6be32a5f7d4d943391cbadbc3cf7a
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 9121
              name: redisexp
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 999
      securityContext:
        runAsUser: 999
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-cache
