apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Redis for storing semi-persistent data like user sessions.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: redis
  name: redis-store
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-store
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: redis-store
    spec:
      containers:
        - name: redis-store
          image: us-docker.pkg.dev/sourcegraph-images/internal/redis-store:7.2.0@sha256:839c62d67edda48af35e577b7fb48624310c23294ef855b66f86312b688a15fb
          terminationMessagePolicy: FallbackToLogsOnError
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: redis
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  PASS_CHECK=$(grep -h "requirepass" /etc/redis/redis.conf | cut -d ' ' -f 2)
                  if [ ! -z "$PASS_CHECK" ]; then
                    export REDISCLI_AUTH="$PASS_CHECK"
                  fi
                  response=$(
                    redis-cli ping
                  )
                  if [ "$response" != "PONG" ]; then
                    echo "$response"
                    exit 1
                  fi
          resources:
            limits:
              cpu: "1"
              memory: 7Gi
            requests:
              cpu: "1"
              memory: 7Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 999
          volumeMounts:
            - mountPath: /redis-data
              name: redis-data
        - name: redis-exporter
          image: us-docker.pkg.dev/sourcegraph-images/internal/redis_exporter:7.2.0@sha256:5584dd2e3702e2041750845e337d6ee8ed690bfa918e79fb71954069abac8b77
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 9121
              name: redisexp
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 999
      securityContext:
        runAsUser: 999
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-store
